### ISSUE TITLE
It doesn´t load package name

### ISSUE THREAD

**Issue by lrea05** [SCasanova/f1dataR#9] opened 2022-08-22 12:18 UTC
When trying to install, it can´t load package name. This message appears: Error: package or namespace load failed for 'f1dataR'. Path argument is considered not valid. Could you help with this?
Thank you!

**Comment by SCasanova** [comment] 2022-08-22 13:33
Hi. Yes absolutely 

Can you send me the exact code you're running to install with the full console output?

Thanks

**Comment by SCasanova** [comment] 2022-08-22 13:46
Ok I think I may know what the issue is. I will try to fix later today. Thanks for bringing it up

**Comment by SCasanova** [comment] 2022-08-23 16:13
Can you also provide your R and RStudio versions please

**Comment by lrea05** [comment] 2022-08-23 16:22
I tried it on R versions 4.1.3, 4.2.0 and 4.2.1.  I don´t use R Studio.

**Comment by lrea05** [comment] 2022-08-24 12:39
I don't know if it can help, but on R version 4.1.3 the error message is a little bit different.

> remotes::install_github("SCasanova/f1dataR")
Downloading GitHub repo SCasanova/f1dataR@HEAD
Running `R CMD build`...
* checking for file 'C:\Users\User\AppData\Local\Temp\RtmpCairjD\remotes3a64277c1396\SCasanova-f1dataR-b603fe1/DESCRIPTION' ... OK
* preparing 'f1dataR':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'f1dataR_0.3.8.tar.gz'
Installing package into ‘C:/Users/User/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'f1dataR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(x) : there is no package called 'memoise'
Error: unable to load R code in package 'f1dataR'
Execution halted
ERROR: lazy loading failed for package 'f1dataR'
* removing 'C:/Users/User/Documents/R/win-library/4.1/f1dataR'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/User/AppData/Local/Temp/RtmpCairjD/file3a642cfd719a/f1dataR_0.3.8.tar.gz’ had non-zero exit status

**Comment by SCasanova** [comment] 2022-10-05 18:26
Try now and let me know if it works please

**Comment by pbulsink** [comment] 2022-11-17 16:35
I can look at this one - might be related to the need for the `memoise` package from the last error trace.

**Comment by pbulsink** [comment] 2022-11-17 17:59
PR #20 might help - the last error by @lrea05 indicated `memoise` issues, and earlier errors might be solved by relying on `reticulate::configure_environment`.

**Comment by pbulsink** [comment] 2023-04-29 00:25
@lrea05 Has this solved your installation issues?

**Comment by lrea05** [comment] 2023-05-01 22:08
Yes, it has worked. Sorry for the wait. Thank you @SCasanova

**Comment by SCasanova** [comment] 2023-05-02 08:33
All thanks to @pbulsink

**Comment by SCasanova** [comment] 2023-05-02 08:35
closed by #20

**Comment by SCasanova** [comment] 2023-05-02 08:35
Closed by #20

**Closed by SCasanova** 2023-05-02 08:35 UTC
Labels: help wanted
